export const products = [
  {
    _id: 1,
    name: "kibal",
    image: "/images/kibal",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 59,
    ratings: 5,
    numReviews: 4,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 2,
    name: "burnik",
    image: "/images/burnik",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 8,
    ratings: 5,
    numReviews: 532,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 3,
    name: "tikti",
    image: "/images/tikti",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 10,
    ratings: 5,
    numReviews: 31,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 4,
    name: "very",
    image: "/images/very",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 100,
    ratings: 2,
    numReviews: 651,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 5,
    name: "buldit",
    image: "/images/buldit",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 22,
    ratings: 3,
    numReviews: 541,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 6,
    name: "balakubak",
    image: "/images/balakubak",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 76,
    ratings: 489,
    numReviews: 21,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 7,
    name: "quate",
    image: "/images/Quate",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 9,
    ratings: 215,
    numReviews: 431,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 8,
    name: "kutu",
    image: "/images/Kutu",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 60,
    ratings: 325,
    numReviews: 123,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 8,
    name: "kulan",
    image: "/images/kulan",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 11,
    ratings: 1,
    numReviews: 131,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 9,
    name: "sipon",
    image: "/images/sipon",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 35,
    ratings: 5,
    numReviews: 1,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 10,
    name: "pita",
    image: "/images/pita",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 35,
    ratings: 5,
    numReviews: 1,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: 11,
    name: "kibal",
    image: "/images/kibal",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    brand: "Apple",
    category: "Glasses",
    price: 15,
    ratings: 5,
    numReviews: 231,
    isNew: true,
    reviews: [],
    stock: 7,
  },
];
